### PR TITLE
STOR-1020: Rebase `external-resizer` to v1.7.0 for OCP 4.13

### PR DESCRIPTION
**Pull request by mpatlasov**
Diff to upstream v1.7.0:
https://github.com/kubernetes-csi/external-resizer/compare/v1.7.0...mpatlasov:rebase-1.7.0

Major changes between 1.6.0 (OCP 4.12) and 1.7.0:

Fix panic in recovery path if marking pvc as resize in progress fails ([#246](https://github.com/kubernetes-csi/external-resizer/pull/246), [@gnufied](https://github.com/gnufied))

Full changelogs:

https://github.com/kubernetes-csi/external-resizer/releases/tag/v1.7.0

@openshift/storage

### CODE REVIEW

**Comment by mpatlasov** [comment]
/retitle STOR-1020: Rebase `external-resizer` to v1.7.0 for OCP 4.13

**Comment by duanwei33** [comment]
Checked the CI results look good for sidecar rebase.

**Pull request merged**
